version: '3.8'

services:
  app:
    restart: unless-stopped
    build: .
    container_name: currency-service
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATA_MONGODB_URI=mongodb://mongo:27017/currency_history
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    restart: unless-stopped
    image: mongo:6.0
    container_name: mongo
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - mongo-data:/data/db

  redis:
    restart: unless-stopped
    image: redis:7.4.2-alpine
    container_name: redis
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp


volumes:
  mongo-data:
