version: '3.8'

services:
  app:
    build: .
    container_name: currency-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATA_MONGODB_URI=mongodb://mongo:27017/currency_history
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: