name: Code coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage report
        run: ./gradlew clean test jacocoTestReport

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3
        with:
          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
